apiVersion: apps/v1
kind: Deployment
metadata:
      name: go-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - image: faliqadlan/sagara:latest
          name: go-app
          env:
            - name: "PORT"
              value: "8000"
            - name: "DB"
              value: "mysql"
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: go-app-secret
            - name: "DB_PORT"
              value: "3306"
            - name: "DB_USERNAME"
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: go-app-secret
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: go-app-secret
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: go-app-secret
            - name: "DB_LOC"
              value: "Asia%2FJakarta"
            - name: "S3_REGION"
              valueFrom:
                secretKeyRef:
                  key: S3_REGION
                  name: go-app-secret
            - name: "S3_ID"
              valueFrom:
                secretKeyRef:
                  key: S3_ID
                  name: go-app-secret
            - name: "S3_SECRET"
              valueFrom:
                secretKeyRef:
                  key: S3_SECRET
                  name: go-app-secret
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  selector:
    app: go-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-app-ingress
  annotations:
    dev.okteto.com/generate-host: "domain"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: go-app-service
          servicePort: 8080